package org.hson.model;

// Generated 17/11/2009 12:24:44 PM by Hibernate Tools 3.2.4.GA


import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import javax.persistence.*;

/**
 * GlParametros generated by hbm2java
 */
@Entity
@Table(name = "GL_PARAMETROS", schema = "MUPI")
public class GlParametros implements java.io.Serializable {

	/**
	 *
	 */
	;
	/**
	 *
	 */
	private static final long serialVersionUID = -6384426139324495855L;
	/**
	 *
	 */

	private String idParametro;
	private String valor;
	private String descripcion;
	private String estRegistro;
	private String editableReg;

	public GlParametros() {
	}

	public GlParametros(String idParametro) {
		this.idParametro = idParametro;
	}

	public GlParametros(String idParametro, String valor) {
		this.idParametro = idParametro;
		this.valor = valor;
	}


	@PrePersist @PreUpdate
	private void preInsercion(){
		if(getIdParametro() != null)
			setIdParametro(getIdParametro().toUpperCase());
		/*if(getValor() != null)
			setValor(getValor().toUpperCase());*/
	}

	@Id
	@Column(name = "ID_PARAMETRO", unique = true, nullable = false, length = 18)
	@NotNull
	@Length(max = 18)
	public String getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(String idParametro) {
		this.idParametro = idParametro;
	}

	@Column(name = "VALOR", length = 18)
	@Length(max = 18)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "EST_REGISTRO", length = 1)
	@Length(max = 1)
	public String getEstRegistro() {
		return this.estRegistro;
	}

	public void setEstRegistro(String estRegistro) {
		this.estRegistro = estRegistro;
	}

	@Column(name = "EDITABLE_REG", length = 1)
	@Length(max = 1)
	public String getEditableReg() {
		return editableReg;
	}

	public void setEditableReg(String editableReg) {
		this.editableReg = editableReg;
	}



}
